services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 django_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings